### ISSUE TITLE
[Badge Submission] OpenInfra Summit Vancouver 2023

### ISSUE THREAD

**Issue by joshsimmons** [phpledge/badging#1]
Event Name: OpenInfra Summit
Link to the Event Website: https://openinfra.dev/summit/vancouver-2023/
Point of Contact: Allison Price @allisonprice

Links to Key Pages: https://openinfra.dev/summit/vancouver-2023/summit-onsite-safety/

Masking: Robust: "Mandatory indoor masks (over nose and mouth) for all attendees except while eating, drinking or when delivering a conference talk."
Vaccines: Robust: "Onsite attendees will be required to be fully vaccinated against the COVID-19 virus. Fully vaccinated is defined as two weeks (14 full days) after the final dose of a WHO-approved vaccine."
Tests: Robust: Participants will be encouraged to test, and directed to sources of tests. Financial aid recipients will be able to receive tests directly from the conference organizers at no cost.
Ventilation: Robust
Alternatives: Robust Policy: Participants who exhibit symptoms or test positive during, or right before, the event have access to no questions asked refunds, exchanges.

Reviewing against badging standard [v2023-01](https://github.com/phpledge/badging/blob/main/versions/2023-01.md)

EDIT: This has been updated, OpenInfra stepped up their testing policy and we've updated the assessment.

**Comment by joshsimmons** [comment]
Kicking the tires on our new process here! Thank you @allisonprice and the OpenInfra team for being such fabulous partners. @sarasafavi and I will review on Monday and proceed from there.

**Comment by sarasafavi** [comment]
reviewed this with @joshsimmons - LGTM!

**Comment by joshsimmons** [comment]
OK, @sarasafavi and I have reviewed this and agree with the assessment, per the v2023-01 standard:

- Masking: robust
- Vaccines: robust
- Tests: no policy
- Ventilation: robust
- Alternatives: robust

I'll take next steps to update our event listing and follow up by email with results. Leaving issue open till that's done.

**Comment by joshsimmons** [comment]
I'm thrilled to report the organizers of OpenInfra Summit Vancouver have taken the opportunity to make further improvements to their Health and Safety policies. They will be recommending all attendees test regularly, providing information about where tests can be procured, and directly provisioning tests to participants who are part of their financial aid program.

With that, we're calling this evaluation wrapped with an updated result, per the v2023-01 standard:

- Masking: robust
- Vaccines: robust
- Tests: robust
- Ventilation: robust
- Alternatives: robust

As before, I'll take next steps to update our event listing and follow up by email with results. Leaving issue open till that's done.

**Comment by joshsimmons** [comment]
To Allison, Thierry, and the rest of the OpenInfra team: congratulations and thank you!

Through your already great work and our collaboration to build on that excellence, the PHPledge team is proud to have you as our first official event signatory AND badge recipient, earning a Robust Policy grade across all five measures: Masks, Vaccines, Tests, Ventilation, and Alternatives. 

We will announce on social tomorrow -- we noticed your migrated account and will make sure to point to that! We don't have fancy graphics yet, but you're welcome to use or remix the attached as you see fit.


Verification: https://github.com/phpledge/badging#openinfra-summit-vancouver-2023
Review discussion: https://github.com/phpledge/badging/issues/1
Suggested badge text:

The OpenInfra Summit Vancouver applied for a [Public Health Pledge](https://publichealthpledge.com/badging) event badge, submitting our health and safety policies to review under the [v2023-01](https://github.com/phpledge/badging/blob/main/versions/2023-01.md) standard. We received a Robust Policy grade for Masking, Vaccines, Tests, Ventilation, and Alternatives ([source](https://github.com/phpledge/badging#openinfra-summit-vancouver-2023)).


With gratitude,
Josh, Sara, Chris, Sage, and the rest of the team
