### ISSUE TITLE
Allow submissions made without the use of a Google form

### ISSUE THREAD

**Issue by marado** [phpledge/badging#10]
Currently submissions must be initiated from https://forms.gle/RxdwwEbzy6DtjY1q7 , which isn't a privacy-friendly option. It would be nice if there were alternatives to that.

**Comment by bluesomewhere** [comment]
This is fantastic feedback, thank you! Since starting the pledge I've gotten familiar with Cryptpad and will be happy to swap to one of their forms. I'll leave this issue open until it's done and I can link to it.

**Comment by bluesomewhere** [comment]
Alrighty, tackling this change today:

- [x] New signatory pledge form
- [x] Updated links on Mastodon profile
- [x] Updated links on website
