### ISSUE TITLE
[Badge Submission] North Bay Python 2023

### ISSUE THREAD

**Issue by joshsimmons** [phpledge/badging#3]
Event Name: North Bay Python
Link to the Event Website: https://2023.northbaypython.org/
Point of Contact: Christopher Neugebauer @chrisjrn

Signing the Pledge: Yes
Links to Key Pages: https://2023.northbaypython.org/health-and-safety-policy

Masking: Robust policy: All participants covered whilst indoors or dense spaces, except presenters on stage, and attendees actively eating or drinking. Three-strike policy for violations.
Vaccines: Efforts Made: Strongly recommended.
Tests: Efforts Made: Tests are available for people with financial need. Importance of testing communicated to all attendees. Requirement for people to not attend should they test positive.
Ventilation: Robust Policy: Event is being held in an open-air barn. CO2 monitors to monitor capacity. Considering hiring fans to aid with air exchange.
Alternatives: Efforts Made: Refunds prorated to days that attendees are unwell. All talks will be video-recorded. A best effort will be made for attendees to communicate with speakers they'd like to ask questions of.

Reviewing against badging standard [v2023-01](https://github.com/phpledge/badging/blob/main/versions/2023-01.md)

**Comment by joshsimmons** [comment]
Thanks for your patience! @sarasafavi and I reviewed this and agree with the assessment, per the v2023-01 standard:

Masking: Robust Policy
Vaccines: Efforts Made
Tests: Efforts Made
Ventilation: Robust Policy
Alternatives: Efforts Made

I'll follow up with the applicant with results and update our event listing. Once the listing is updated, I'll follow up on this issue and close it out.

**Comment by bluesomewhere** [comment]
To Chris and the rest of the North Bay Python team: congratulations and thank you!

After reviewing your Health and Safety policy, the PHPledge team is proud to award you a Robust Policy grade across Masking and Ventilation, and an Efforts Made grade for Vaccines, Tests, and Alternatives.

We will announce on social shortly!

Verification: https://github.com/phpledge/badging#north-bay-python-2023
Review discussion: https://github.com/phpledge/badging/issues/3
Suggested badge text:

North Bay Python applied for a [Public Health Pledge](https://publichealthpledge.com/badging) event badge, submitting our health and safety policies to review under the [v2023-01](https://github.com/phpledge/badging/blob/main/versions/2023-01.md) standard. We received a Robust Policy grade for Masking and Ventilation, and Alternatives, and an Efforts Made grade for Vaccines, Tests, and Alternatives ([source](https://github.com/phpledge/badging#north-bay-python-2023)).

With gratitude,
Josh, Sara, Chris, Sage, and the rest of the team
